import { db } from './index.js';
import { plugins, pluginRelations } from './schema.js';
import type { PluginManifest } from '@chef-ai/shared';

const SEED_PLUGINS: Array<{
  name: string;
  slug: string;
  version: string;
  description: string;
  type: 'tool' | 'behavior' | 'integration' | 'model-config';
  category: string;
  manifest: PluginManifest;
}> = [
  {
    name: '@chef-ai/web-search',
    slug: 'web-search',
    version: '1.0.0',
    description: 'Search the web using Tavily, Exa, or Brave Search',
    type: 'tool',
    category: 'search',
    manifest: {
      name: '@chef-ai/web-search',
      version: '1.0.0',
      description: 'Search the web using Tavily, Exa, or Brave Search',
      type: 'tool',
      category: 'search',
      tags: ['web', 'search', 'research'],
      capabilities_provided: ['web:search', 'web:fetch-url', 'web:extract-content'],
      capabilities_unlocked_with: {
        '@chef-ai/browser-use': ['web:deep-extract', 'web:paginated-search'],
        '@chef-ai/csv-processor': ['data:search-to-table'],
      },
      requires: [],
      enhances: ['@chef-ai/browser-use'],
      conflicts: [],
      affinity: { research: 95, coding: 40, writing: 60, 'data-analysis': 70, automation: 50, content: 55, communication: 30 },
      pricing: { external_apis: [{ name: 'Tavily', cost_per_call: 0.001 }], compute_intensity: 'light' },
      mcp: { transport: 'stdio', command: 'node', args: ['dist/server.js'], env: { TAVILY_API_KEY: { required: true, source: 'platform' } } },
      config: { schema: { maxResults: { type: 'number', min: 1, max: 50, default: 10 } } },
    },
  },
  {
    name: '@chef-ai/browser-use',
    slug: 'browser-use',
    version: '1.0.0',
    description: 'Navigate, click, and extract content from web pages',
    type: 'tool',
    category: 'browser',
    manifest: {
      name: '@chef-ai/browser-use',
      version: '1.0.0',
      description: 'Navigate, click, and extract content from web pages',
      type: 'tool',
      category: 'browser',
      tags: ['browser', 'scraping', 'navigation'],
      capabilities_provided: ['web:browse', 'web:click', 'web:extract-page'],
      capabilities_unlocked_with: { '@chef-ai/screenshot-capture': ['web:visual-capture'] },
      requires: [],
      enhances: ['@chef-ai/web-search'],
      conflicts: [],
      affinity: { research: 85, coding: 30, writing: 40, 'data-analysis': 60, automation: 70, content: 45, communication: 20 },
      pricing: { external_apis: [], compute_intensity: 'medium' },
      mcp: { transport: 'stdio', command: 'node', args: ['dist/server.js'], env: {} },
      config: { schema: { headless: { type: 'boolean', default: true } } },
    },
  },
  {
    name: '@chef-ai/file-ops',
    slug: 'file-ops',
    version: '1.0.0',
    description: 'Read, write, and list files in sandbox',
    type: 'tool',
    category: 'file',
    manifest: {
      name: '@chef-ai/file-ops',
      version: '1.0.0',
      description: 'Read, write, and list files in sandbox',
      type: 'tool',
      category: 'file',
      tags: ['file', 'read', 'write', 'filesystem'],
      capabilities_provided: ['file:read', 'file:write', 'file:list'],
      capabilities_unlocked_with: {},
      requires: [],
      enhances: ['@chef-ai/code-executor'],
      conflicts: [],
      affinity: { research: 40, coding: 90, writing: 50, 'data-analysis': 60, automation: 80, content: 40, communication: 20 },
      pricing: { external_apis: [], compute_intensity: 'light' },
      mcp: { transport: 'stdio', command: 'node', args: ['dist/server.js'], env: {} },
      config: { schema: {} },
    },
  },
  {
    name: '@chef-ai/code-executor',
    slug: 'code-executor',
    version: '1.0.0',
    description: 'Execute Python, Node.js, or Bash code in sandbox',
    type: 'tool',
    category: 'code',
    manifest: {
      name: '@chef-ai/code-executor',
      version: '1.0.0',
      description: 'Execute Python, Node.js, or Bash code in sandbox',
      type: 'tool',
      category: 'code',
      tags: ['code', 'python', 'nodejs', 'bash', 'execute'],
      capabilities_provided: ['code:execute-python', 'code:execute-node', 'code:execute-bash'],
      capabilities_unlocked_with: { '@chef-ai/file-ops': ['code:persist-output'] },
      requires: [],
      enhances: ['@chef-ai/csv-processor', '@chef-ai/database-query'],
      conflicts: [],
      affinity: { research: 30, coding: 95, writing: 20, 'data-analysis': 85, automation: 75, content: 15, communication: 10 },
      pricing: { external_apis: [], compute_intensity: 'medium' },
      mcp: { transport: 'stdio', command: 'node', args: ['dist/server.js'], env: {} },
      config: { schema: { timeout: { type: 'number', default: 30 } } },
    },
  },
  {
    name: '@chef-ai/markdown-export',
    slug: 'markdown-export',
    version: '1.0.0',
    description: 'Generate formatted markdown reports and documents',
    type: 'tool',
    category: 'file',
    manifest: {
      name: '@chef-ai/markdown-export',
      version: '1.0.0',
      description: 'Generate formatted markdown reports and documents',
      type: 'tool',
      category: 'file',
      tags: ['markdown', 'report', 'export', 'document'],
      capabilities_provided: ['file:export-markdown', 'file:export-report'],
      capabilities_unlocked_with: {},
      requires: [],
      enhances: [],
      conflicts: [],
      affinity: { research: 80, coding: 30, writing: 95, 'data-analysis': 70, automation: 40, content: 90, communication: 50 },
      pricing: { external_apis: [], compute_intensity: 'light' },
      mcp: { transport: 'stdio', command: 'node', args: ['dist/server.js'], env: {} },
      config: { schema: { template: { type: 'string', default: 'default' } } },
    },
  },
  {
    name: '@chef-ai/pdf-reader',
    slug: 'pdf-reader',
    version: '1.0.0',
    description: 'Extract text and tables from PDF documents',
    type: 'tool',
    category: 'file',
    manifest: {
      name: '@chef-ai/pdf-reader',
      version: '1.0.0',
      description: 'Extract text and tables from PDF documents',
      type: 'tool',
      category: 'file',
      tags: ['pdf', 'extract', 'reader'],
      capabilities_provided: ['file:read-pdf', 'data:extract-tables'],
      capabilities_unlocked_with: { '@chef-ai/image-analyzer': ['file:read-scanned-pdf'] },
      requires: [],
      enhances: [],
      conflicts: [],
      affinity: { research: 75, coding: 20, writing: 40, 'data-analysis': 80, automation: 30, content: 35, communication: 20 },
      pricing: { external_apis: [], compute_intensity: 'light' },
      mcp: { transport: 'stdio', command: 'node', args: ['dist/server.js'], env: {} },
      config: { schema: {} },
    },
  },
  {
    name: '@chef-ai/image-analyzer',
    slug: 'image-analyzer',
    version: '1.0.0',
    description: 'Analyze images using Claude Vision',
    type: 'tool',
    category: 'media',
    manifest: {
      name: '@chef-ai/image-analyzer',
      version: '1.0.0',
      description: 'Analyze images using Claude Vision',
      type: 'tool',
      category: 'media',
      tags: ['image', 'vision', 'analyze', 'ocr'],
      capabilities_provided: ['media:analyze-image', 'media:ocr'],
      capabilities_unlocked_with: {},
      requires: [],
      enhances: ['@chef-ai/pdf-reader', '@chef-ai/screenshot-capture'],
      conflicts: [],
      affinity: { research: 60, coding: 20, writing: 30, 'data-analysis': 65, automation: 25, content: 70, communication: 15 },
      pricing: { external_apis: [], compute_intensity: 'medium' },
      mcp: { transport: 'stdio', command: 'node', args: ['dist/server.js'], env: {} },
      config: { schema: {} },
    },
  },
  {
    name: '@chef-ai/csv-processor',
    slug: 'csv-processor',
    version: '1.0.0',
    description: 'Parse, transform, and query CSV data',
    type: 'tool',
    category: 'data',
    manifest: {
      name: '@chef-ai/csv-processor',
      version: '1.0.0',
      description: 'Parse, transform, and query CSV data',
      type: 'tool',
      category: 'data',
      tags: ['csv', 'data', 'table', 'transform'],
      capabilities_provided: ['data:parse-csv', 'data:transform', 'data:tabulate'],
      capabilities_unlocked_with: {},
      requires: [],
      enhances: ['@chef-ai/markdown-export'],
      conflicts: [],
      affinity: { research: 60, coding: 40, writing: 30, 'data-analysis': 95, automation: 50, content: 25, communication: 15 },
      pricing: { external_apis: [], compute_intensity: 'light' },
      mcp: { transport: 'stdio', command: 'node', args: ['dist/server.js'], env: {} },
      config: { schema: {} },
    },
  },
  {
    name: '@chef-ai/email-sender',
    slug: 'email-sender',
    version: '1.0.0',
    description: 'Send emails via Resend',
    type: 'integration',
    category: 'comms',
    manifest: {
      name: '@chef-ai/email-sender',
      version: '1.0.0',
      description: 'Send emails via Resend',
      type: 'integration',
      category: 'comms',
      tags: ['email', 'send', 'notification'],
      capabilities_provided: ['comms:send-email'],
      capabilities_unlocked_with: {},
      requires: [],
      enhances: [],
      conflicts: [],
      affinity: { research: 10, coding: 10, writing: 30, 'data-analysis': 10, automation: 85, content: 40, communication: 95 },
      pricing: { external_apis: [{ name: 'Resend', cost_per_call: 0.001 }], compute_intensity: 'light' },
      mcp: { transport: 'stdio', command: 'node', args: ['dist/server.js'], env: { RESEND_API_KEY: { required: true, source: 'platform' } } },
      config: { schema: {} },
    },
  },
  {
    name: '@chef-ai/calendar-reader',
    slug: 'calendar-reader',
    version: '1.0.0',
    description: 'Read Google or Outlook calendar events',
    type: 'integration',
    category: 'comms',
    manifest: {
      name: '@chef-ai/calendar-reader',
      version: '1.0.0',
      description: 'Read Google or Outlook calendar events',
      type: 'integration',
      category: 'comms',
      tags: ['calendar', 'google', 'outlook', 'events'],
      capabilities_provided: ['comms:read-calendar'],
      capabilities_unlocked_with: {},
      requires: [],
      enhances: ['@chef-ai/email-sender'],
      conflicts: [],
      affinity: { research: 15, coding: 10, writing: 20, 'data-analysis': 20, automation: 80, content: 15, communication: 85 },
      pricing: { external_apis: [], compute_intensity: 'light' },
      mcp: { transport: 'stdio', command: 'node', args: ['dist/server.js'], env: {} },
      config: { schema: {} },
    },
  },
  {
    name: '@chef-ai/notion-connector',
    slug: 'notion-connector',
    version: '1.0.0',
    description: 'Read and write Notion pages and databases',
    type: 'integration',
    category: 'comms',
    manifest: {
      name: '@chef-ai/notion-connector',
      version: '1.0.0',
      description: 'Read and write Notion pages and databases',
      type: 'integration',
      category: 'comms',
      tags: ['notion', 'pages', 'database', 'notes'],
      capabilities_provided: ['comms:read-notion', 'comms:write-notion'],
      capabilities_unlocked_with: {},
      requires: [],
      enhances: [],
      conflicts: [],
      affinity: { research: 40, coding: 20, writing: 60, 'data-analysis': 40, automation: 65, content: 70, communication: 50 },
      pricing: { external_apis: [], compute_intensity: 'light' },
      mcp: { transport: 'stdio', command: 'node', args: ['dist/server.js'], env: { NOTION_API_KEY: { required: true, source: 'platform' } } },
      config: { schema: {} },
    },
  },
  {
    name: '@chef-ai/github-ops',
    slug: 'github-ops',
    version: '1.0.0',
    description: 'Create issues, PRs, and read code from GitHub',
    type: 'integration',
    category: 'devtools',
    manifest: {
      name: '@chef-ai/github-ops',
      version: '1.0.0',
      description: 'Create issues, PRs, and read code from GitHub',
      type: 'integration',
      category: 'devtools',
      tags: ['github', 'git', 'issues', 'pr', 'code'],
      capabilities_provided: ['devtools:github-issues', 'devtools:github-pr', 'devtools:github-read'],
      capabilities_unlocked_with: { '@chef-ai/code-executor': ['devtools:github-ci'] },
      requires: [],
      enhances: ['@chef-ai/code-executor'],
      conflicts: [],
      affinity: { research: 30, coding: 90, writing: 20, 'data-analysis': 20, automation: 70, content: 15, communication: 30 },
      pricing: { external_apis: [], compute_intensity: 'light' },
      mcp: { transport: 'stdio', command: 'node', args: ['dist/server.js'], env: { GITHUB_TOKEN: { required: true, source: 'platform' } } },
      config: { schema: {} },
    },
  },
  {
    name: '@chef-ai/database-query',
    slug: 'database-query',
    version: '1.0.0',
    description: 'Query PostgreSQL, MySQL, or SQLite databases',
    type: 'tool',
    category: 'data',
    manifest: {
      name: '@chef-ai/database-query',
      version: '1.0.0',
      description: 'Query PostgreSQL, MySQL, or SQLite databases',
      type: 'tool',
      category: 'data',
      tags: ['database', 'sql', 'query', 'postgresql'],
      capabilities_provided: ['data:query-sql', 'data:read-database'],
      capabilities_unlocked_with: {},
      requires: [],
      enhances: ['@chef-ai/csv-processor'],
      conflicts: [],
      affinity: { research: 30, coding: 70, writing: 10, 'data-analysis': 95, automation: 50, content: 10, communication: 10 },
      pricing: { external_apis: [], compute_intensity: 'light' },
      mcp: { transport: 'stdio', command: 'node', args: ['dist/server.js'], env: {} },
      config: { schema: {} },
    },
  },
  {
    name: '@chef-ai/screenshot-capture',
    slug: 'screenshot-capture',
    version: '1.0.0',
    description: 'Capture screenshots of URLs or pages',
    type: 'tool',
    category: 'media',
    manifest: {
      name: '@chef-ai/screenshot-capture',
      version: '1.0.0',
      description: 'Capture screenshots of URLs or pages',
      type: 'tool',
      category: 'media',
      tags: ['screenshot', 'capture', 'image', 'url'],
      capabilities_provided: ['media:screenshot'],
      capabilities_unlocked_with: { '@chef-ai/image-analyzer': ['media:screenshot-to-data'] },
      requires: [],
      enhances: ['@chef-ai/browser-use'],
      conflicts: [],
      affinity: { research: 55, coding: 20, writing: 30, 'data-analysis': 40, automation: 45, content: 65, communication: 25 },
      pricing: { external_apis: [], compute_intensity: 'medium' },
      mcp: { transport: 'stdio', command: 'node', args: ['dist/server.js'], env: {} },
      config: { schema: {} },
    },
  },
  {
    name: '@chef-ai/text-to-speech',
    slug: 'text-to-speech',
    version: '1.0.0',
    description: 'Generate audio from text using ElevenLabs',
    type: 'tool',
    category: 'media',
    manifest: {
      name: '@chef-ai/text-to-speech',
      version: '1.0.0',
      description: 'Generate audio from text using ElevenLabs',
      type: 'tool',
      category: 'media',
      tags: ['tts', 'audio', 'speech', 'voice'],
      capabilities_provided: ['media:text-to-speech'],
      capabilities_unlocked_with: {},
      requires: [],
      enhances: [],
      conflicts: [],
      affinity: { research: 10, coding: 5, writing: 30, 'data-analysis': 5, automation: 30, content: 80, communication: 40 },
      pricing: { external_apis: [{ name: 'ElevenLabs', cost_per_call: 0.01 }], compute_intensity: 'light' },
      mcp: { transport: 'stdio', command: 'node', args: ['dist/server.js'], env: { ELEVENLABS_API_KEY: { required: true, source: 'platform' } } },
      config: { schema: {} },
    },
  },
];

const SEED_RELATIONS: Array<{
  pluginA: string;
  pluginB: string;
  type: 'hard-conflict' | 'soft-warning' | 'enhancement' | 'unlocks';
  description: string;
  capabilitiesUnlocked?: string[];
}> = [
  { pluginA: '@chef-ai/web-search', pluginB: '@chef-ai/browser-use', type: 'enhancement', description: 'Web Search enhances Browser Use with targeted search before navigation' },
  { pluginA: '@chef-ai/browser-use', pluginB: '@chef-ai/web-search', type: 'enhancement', description: 'Browser Use enhances Web Search with deep page extraction' },
  { pluginA: '@chef-ai/web-search', pluginB: '@chef-ai/browser-use', type: 'unlocks', description: 'Combining Web Search + Browser Use unlocks deep extraction and paginated search', capabilitiesUnlocked: ['web:deep-extract', 'web:paginated-search'] },
  { pluginA: '@chef-ai/web-search', pluginB: '@chef-ai/csv-processor', type: 'unlocks', description: 'Combining Web Search + CSV Processor unlocks search-to-table pipeline', capabilitiesUnlocked: ['data:search-to-table'] },
  { pluginA: '@chef-ai/file-ops', pluginB: '@chef-ai/code-executor', type: 'enhancement', description: 'File Ops enhances Code Executor with persistent file I/O' },
  { pluginA: '@chef-ai/code-executor', pluginB: '@chef-ai/file-ops', type: 'unlocks', description: 'Combining Code Executor + File Ops unlocks persisted code output', capabilitiesUnlocked: ['code:persist-output'] },
  { pluginA: '@chef-ai/csv-processor', pluginB: '@chef-ai/markdown-export', type: 'enhancement', description: 'CSV Processor enhances Markdown Export with table formatting' },
  { pluginA: '@chef-ai/image-analyzer', pluginB: '@chef-ai/pdf-reader', type: 'enhancement', description: 'Image Analyzer enhances PDF Reader with scanned PDF support' },
  { pluginA: '@chef-ai/pdf-reader', pluginB: '@chef-ai/image-analyzer', type: 'unlocks', description: 'Combining PDF Reader + Image Analyzer unlocks scanned PDF reading', capabilitiesUnlocked: ['file:read-scanned-pdf'] },
  { pluginA: '@chef-ai/screenshot-capture', pluginB: '@chef-ai/image-analyzer', type: 'unlocks', description: 'Combining Screenshot Capture + Image Analyzer unlocks screenshot-to-data', capabilitiesUnlocked: ['media:screenshot-to-data'] },
  { pluginA: '@chef-ai/screenshot-capture', pluginB: '@chef-ai/browser-use', type: 'enhancement', description: 'Screenshot Capture enhances Browser Use with visual capture' },
  { pluginA: '@chef-ai/github-ops', pluginB: '@chef-ai/code-executor', type: 'enhancement', description: 'GitHub Ops enhances Code Executor with repository context' },
  { pluginA: '@chef-ai/github-ops', pluginB: '@chef-ai/code-executor', type: 'unlocks', description: 'Combining GitHub Ops + Code Executor unlocks CI-like workflows', capabilitiesUnlocked: ['devtools:github-ci'] },
  { pluginA: '@chef-ai/calendar-reader', pluginB: '@chef-ai/email-sender', type: 'enhancement', description: 'Calendar Reader enhances Email Sender with event-based triggers' },
  { pluginA: '@chef-ai/database-query', pluginB: '@chef-ai/csv-processor', type: 'enhancement', description: 'Database Query enhances CSV Processor with live data sources' },
];

async function seed() {
  console.log('Seeding plugins...');

  for (const p of SEED_PLUGINS) {
    await db
      .insert(plugins)
      .values({
        name: p.name,
        slug: p.slug,
        version: p.version,
        description: p.description,
        type: p.type,
        category: p.category,
        manifest: p.manifest,
        isBundled: true,
      })
      .onConflictDoUpdate({
        target: plugins.name,
        set: { manifest: p.manifest, version: p.version, description: p.description },
      });
  }

  console.log(`Seeded ${SEED_PLUGINS.length} plugins`);

  const allPlugins = await db.select().from(plugins);
  const pluginMap = new Map(allPlugins.map((p) => [p.name, p.id]));

  for (const r of SEED_RELATIONS) {
    const aId = pluginMap.get(r.pluginA);
    const bId = pluginMap.get(r.pluginB);
    if (!aId || !bId) continue;

    await db
      .insert(pluginRelations)
      .values({
        pluginA: aId,
        pluginB: bId,
        type: r.type,
        description: r.description,
        capabilitiesUnlocked: r.capabilitiesUnlocked ?? null,
      })
      .onConflictDoNothing();
  }

  console.log(`Seeded ${SEED_RELATIONS.length} plugin relations`);
  process.exit(0);
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
